version: '2'
# Work around CodeClimate's inability to use Rubocop's inherit_gem directive:
# https://github.com/codeclimate/codeclimate-rubocop/issues/71#issuecomment-635055223
prepare:
  fetch:
    - url: https://raw.githubusercontent.com/GSA/searchgov_style/main/.default.yml
      path: .rubocop-https---raw-githubusercontent-com-GSA-searchgov-style-main--default-yml
plugins:
  brakeman:
    enabled: true
  bundler-audit:
    enabled: true
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - ruby
    exclude_patterns:
    - "spec/"
  eslint:
    enabled: true
  fixme:
    enabled: true
  rubocop:
    enabled: true
    channel: rubocop-1-48-1
exclude_patterns:
- bin/
- vendor/
- coverage/
