version: '3.8'

services:
  elasticsearch6:
    build:
      context: ./
      dockerfile: Dockerfile.elasticsearch6
    environment:
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es_6_data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

  elasticsearch7:
    build:
      context: ./
      dockerfile: Dockerfile.elasticsearch7
    environment:
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es_7_data:/usr/share/elasticsearch/data
    ports:
      - 9271:9200

  kibana6:
    image: docker.elastic.co/kibana/kibana:6.8.13
    depends_on:
      - elasticsearch6
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch6:9200

  kibana7:
    image: docker.elastic.co/kibana/kibana:7.10.1
    depends_on:
      - elasticsearch7
    ports:
      - 5671:5601
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch7:9200

volumes:
  es_6_data:
  es_7_data:
