default: &DEFAULT
  hosts:
    - <%= ENV['ES_HOST'] || 'localhost:9200' %>
  user: elastic
  password: changeme

development:
  <<: *DEFAULT

test:
  <<: *DEFAULT

production:
# This file is overwritten by Chef during a deploy. Any production
# changes should be made in the cookbooks.
