default: &DEFAULT
  user: elastic
  password: changeme

development:
  <<: *DEFAULT
  hosts:
    - localhost:9256

test:
  <<: *DEFAULT
  hosts:
    - localhost:9256

production:
  <<: *DEFAULT
  hosts:
    - localhost
